### ISSUE TITLE
Point not rendering

### ISSUE THREAD

**Issue by parsoyaarihant** [p5py/p5#106]
Point is not rendered on the canvas. 

**To Reproduce**
```python
from p5 import *

def draw():
	size(640, 360)
	background(0)

	stroke(255)
	point(width * 0.5, height * 0.1)
	point(width * 0.5, height * 0.9)

if __name__ == '__main__':
    run()
```

**Expected behaviour**
Two white points should be displayed on the screen

**Screenshots**
![Screenshot 2019-05-15 at 3 47 40 PM](https://user-images.githubusercontent.com/15258498/57768215-c8a27d00-7728-11e9-97e0-ce720d2554d2.png)

**System information:**
 - Python version: 3.7
 - Operating system: Mac Mojave

**Comment by jeremydouglass** [comment]
@parsoyaarihant, just out of curiosity, when you close things like this, are you closing wontfix, or is it being closed by something?

If you add the text "Fixes #" and then the issue number (106) to any related commit / pull / merge -- or a later comment on a commit / pull / merge -- then it will be cross-linked here so that it is clear if/how the issue was resolved.

**Comment by parsoyaarihant** [comment]
@jeremydouglass , while working on another bug, I was able to render points on the canvas which led me to believe that this issue is fixed and I closed the issue. However, it was not fixed. I have submitted a commit which fixed this issue. Thanks for pointing this out.
