### ISSUE TITLE
Why is the syntax different from processing

### ISSUE THREAD

**Issue by hunar1997** [p5py/p5#130]
I searched the readme and the issues and couldn't find my question, i just found p5py and tried to transfer a python mode project within processing which uses jython, and it didn't work. The error message was confusing, but i found that the reason was that in processing `circle(x,y,r)` is correct but in p5py it must be `circle((x,y),r)`

but why? wouldn't it be better to make the syntax the same? to attract processing users and make it easy for them?

Thanks :D

**Comment by jeremydouglass** [comment]
Personally I think that seems like a reasonable expectation.

`func(a,b,c)` is generally the way you do it in Processing Java, processing.py, p5.js, Processing.R, JRubyArt et cetera -- circle is a recent addition in Processing 3.x, but ellipse() or rect() work the same way in everything -- not rect((x,y),w,h) but rect(x,y,w,h). This also makes sense with the various "mode" parts of the API, like ellipseMode and rectMode, which can change what the arguments do.

No reason you couldn't support both that AND PVectors / points / tuples / whatever signatures, but flat argument lists is the default in every other API.

**Comment by parsoyaarihant** [comment]
> The error message was confusing, but i found that the reason was that in processing circle(x,y,r) is correct but in p5py it must be circle((x,y),r)

This is something I found confusion too. I believe we need to have a bigger discussion about it. 
Adding @abhikpal to the conversation.

> This also makes sense with the various "mode" parts of the API, like ellipseMode and rectMode, which can change what the arguments do.

The names of the '"mode" functions were originally created to match the Pythons [PEP 8](https://www.python.org/dev/peps/pep-0008/) conventions. Hence, the convention has persisted. We contacted Ben Fry regarding this issue and he approved the current PEP 8 convention.

**Comment by swirly** [comment]
Found this very disturbing for teaching. Have to explain tuples far too soon to use this

**Comment by GoToLoop** [comment]
> No reason you couldn't support both that AND PVectors / points / tuples / whatever signatures,

That's exactly what I did very recently in a Processing forum thread:
https://Discourse.Processing.org/t/get-perpendicular-angle/14067/14

Functions **line()**, **circle()** & **text()** were reimplemented w/ a new signature, but w/o losing the original 1.

For the **circle()**'s new implementation below, besides keeping its **_PApplet_**'s original 3-parameter signature, it also accepts any object containing attributes _x_ & _y_.

For example: **_PVector_**, other 3rd-party libraries' classes like **_Vec2_** & **_Vec3_** and even Java's builtin classes like **_Point_** and such: 
```python
add_library('box2d_processing')
from org.jbox2d.common import Vec2, Vec3

from java.awt import Point

def setup():
    noLoop()

    x = width  >> 1
    y = height >> 1
    d = min(x, y)

    circle(x, y, d)
    circle(PVector(x, y), d)

    circle(Vec2(x, y), d)
    circle(Vec3(x, y, 0), d)

    circle(Point(x, y), d)
    circle(Point.Float(x, y), d)
    circle(Point.Double(x, y), d)


def circle(p, diam, *args):
    this.circle(p, diam, *args) if args else this.circle(p.x, p.y, diam)
```
Obviously, those Java and its 3rd-party libraries are irrelevant for p5py.

But it shows how flexible this single statement is already capable of in Jython under Python Mode:
`this.circle(p, diam, *args) if args else this.circle(p.x, p.y, diam)`

However, in order to implement other signatures, like tuples, lists, dics, etc., we're gonna need to add more conditional statements to it:
```python
add_library('box2d_processing')
from org.jbox2d.common import Vec2, Vec3

from java.util import ArrayList, Vector, LinkedList, HashMap, TreeMap
from java.awt import Point

def setup():
    noLoop()

    x = width  >> 1
    y = height >> 1
    d = min(x, y)

    circle(x, y, d)
    circle(PVector(x, y), d)

    circle(Vec2(x, y), d)
    circle(Vec3(x, y, 0), d)

    circle(Point(x, y), d)
    circle(Point.Float(x, y), d)
    circle(Point.Double(x, y), d)

    circle((x, y), d)
    circle([x, y], d)
    circle({ 'x': x, 'y': y }, d)

    circle(ArrayList((x, y)), d)
    circle(Vector((x, y)), d)
    circle(LinkedList((x, y)), d)
    circle(HashMap({ 'x': x, 'y': y }), d)
    circle(TreeMap({ 'x': x, 'y': y }), d)


def circle(p, diam, *args):
    if args: this.circle(p, diam, *args)
    elif hasattr(p, 'y'): this.circle(p.x, p.y, diam)
    elif 'y' in p: this.circle(p['x'], p['y'], diam)
    else: this.circle(p[0], p[1], diam)
```
But at least now it covers so much more container types than before!
