### ISSUE TITLE
no_loop incorrectly allows an extra draw frame

### ISSUE THREAD

**Issue by jeremydouglass** [p5py/p5#158]
**Describe the bug**
`no_loop` should stop draw from being called after the function in which it is called returns. Instead, it draws another frame, *then* stops draw.

**To Reproduce**
```
from p5 import *
def setup():
    size(400,400)
def draw():
    print("frame",frame_count)
    no_loop()
if __name__ == '__main__':
    run()
```

**Expected behavior**

Should print "frame 1".
Instead prints "frame 1 frame 2".

**System information:**
 - p5 release 0.6.0
 - Python version:3.7.7
 - Operating system: macOS 10.12

**Comment by marcrleonard** [comment]
I can confirm I am seeing similar behavior.

**Comment by tushar5526** [comment]
I am seeing the same behaviour too on ubuntu 18.04, I want to work on this issue, I am new to this project, I have some questions regarding the project, is there any discord or slack or any other forum specifically for p5py, where I can ask questions regarding the project ? 

Where are the guidelines for naming the files, convention for naming variables and other general guidelines to contribute ?

**Comment by jeremydouglass** [comment]
> is there any discord or slack or any other forum specifically for p5py

@parsoyaarihant @abhikpal -- do you have a preferred place for p5py dev questions other than issues on this repo?

For many questions on Processing programming in general -- including p5py -- you may also post to the Processing forum -- https://discourse.processing.org/

**Comment by tushar5526** [comment]
I have found the bug , and know the fix, draw() is not being called again , it is working properly 
it is just frame_count is being updated in each loop, without checking whether no_loop() [which sets another bool named looping ] is false or not , 

example 

#without checking whether or not looping is false or not 
frame_count += 1

#but draw() is checking whether looping is true or false
if looping:
  draw()

**Comment by tushar5526** [comment]
Found the bug and know the fix, how to assign the issue to myself or should I directly send the pull req

**Comment by tushar5526** [comment]
@parsoyaarihant This merge is causing problem, if we call no_loop() in setup() method, things are coded in a way to draw another frame when we use no_loop(), so if there is a no_loop() present in draw() , first draw() is called initially the no_loop() is encountered, but no_loop() is set in a way so that it calls exactly one another frame, hence we are getting the bug mentioned in this issue

no_loop() was made to draw another loop because, if no_loop() is present in setup(), then first setup() is called, which calls no_loop(), no_loop() do not let the draw() function get called in the next the next iteration(hence nothing would be drawn after that) that's why the developer made a check that no_loop() will draw one more frame so if no_loop() is present in setup() things will work properly

Possible fixes for this bug and the problem I mentioned is, if no_loop() was called from setup() then we call draw() in other iteration , and if it is called in draw(), then we dont call another draw_loop() in the next iteration, or better let this bug we there !

**Comment by tushar5526** [comment]
I am creating a separate issue for this

**Comment by jeremydouglass** [comment]
Should this be reopened? I'm not clear where things are with the backed out PR.
