### ISSUE TITLE
Possibly some rendering bug

### ISSUE THREAD

**Issue by mrkvicka22** [p5py/p5#182]
**Describe the bug**
I am trying to show an chess board and first row never renders correctly.

**To Reproduce**
basically just copy paste this code. There is some console printing going on to sort of prove that there is no problem with the algorithm to print the chessboard.
```
from p5 import *

SCALAR = 200


def setup():
    size(SCALAR*8, SCALAR*8)
    no_loop()


def draw():

    for i in range(8):
        line = ""
        for j in range(8):
            rect((i * SCALAR, j * SCALAR), SCALAR, SCALAR)
            if (i+j) % 2 == 0:
                fill(0)
                line+="B"
            else:
                fill(255)
                line+="W"
        print(line,str(i))


run()
```

**Expected behavior**
Expected would be to show a chessboard once with no loop.

**Screenshots**
![image](https://user-images.githubusercontent.com/40635376/84767761-417ea300-afd3-11ea-8ef9-a1fc868d9388.png)

**System information:**
 - p5 release (version number or latest commit): 0.6.0
 - Python version: 3.6.7
 - Operating system: Windows 10

**Comment by parsoyaarihant** [comment]
Try

```python
from p5 import *

SCALAR = 200


def setup():
	size(SCALAR*8, SCALAR*8)

def draw():
	for i in range(8):
		line = ""
		for j in range(8):
			if (i+j) % 2 == 0:
				fill(0)
				line+="B"
			else:
				fill(255)
				line+="W"
			rect((j * SCALAR, i * SCALAR), SCALAR, SCALAR)
		print(line,str(i))


run()
```

**Comment by jeremydouglass** [comment]
@parsoyaarihant do you prefer to answer programming-question issues here, or redirect then to the forum? I ask because most of the other modes redirect all code questions to the Processing forum, but right now p5py does not -- although at present it is a newer project and may have a smaller user base, so it might also make sense to just address everything here....

**Comment by parsoyaarihant** [comment]
@jeremydouglass I personally don't have any preference. I think the forum is better than Github because it is easier to find existing issues from Google.

But, I only rely on my email notifications for anything relevant to me. And I wont get any notification from the forum unless I am tagged in a comment. I can subscribe to a tag on the forum. But, so far there is no separate p5py tag.

**Comment by jeremydouglass** [comment]
Good point. For now we have been leaving all the pys in one channel, but we could make a separate p5py channel or tag.
