### ISSUE TITLE
event.change incorrect behavior as per documentation.

### ISSUE THREAD

**Issue by tushar5526** [p5py/p5#347]
**Describe the bug**
Currently `event.change` contains the change in mouse position when the cursor is pressed. I think there is no need for this as there is no matching API in p5.js reference.

Also, `event.change` is calculated using `press_event` and `last_event` which are vispy-specific variables and would hinder in reusing the events module for other renderers. 

**To Reproduce**
(https://github.com/p5py/p5/blob/master/p5/sketch/events.py#L244)

**Proposed Solution**
Remove the `event.change` from MouseEvent

**Comment by tushar5526** [comment]
I will probably cover this in #344

**Comment by tushar5526** [comment]
Also, there is no need for `mouse_is_dragging`, it does not make sense to have that and it seems to work in the opposite way. 

We could simply use `mouse_is_pressed` to find whether the mouse is dragging or not. 

p5.js equivalent
```
function draw() {
  background(237, 34, 93);
  fill(0);

  if (mouseIsPressed === true) {
    ellipse(50,50, mouseX, mouseY);
  } else {
    rect(25, 25, 50, 50);
  }

  print(mouseIsPressed);
}
```

**Comment by ziyaointl** [comment]
Yes, I think removing `event.change` is fine, given that it's fairly easy for the end user to obtain the same information themseves be keeping the last position in a separate variable. This said, I would recommend separating the deletion of this variable in a seprate PR for vispy so that it's easier to review (and potentially easier revert if we happen to find out later that there are lots of people who find this feature useful).
