### ISSUE TITLE
Color parsing doesn't work.

### ISSUE THREAD

**Issue by artyprog** [p5py/p5#7]
Thank you very much for P5

I have been missing NodeBox 2D on Mac.
I really hope  your project will grow and succeed.
One of the feature I am waiting the most is the export to PDF

For now here is the bug I encounter

Regards

**Test script:**

```python
# put your test script here
from p5 import *

c = Color(255)

```

**Errors produced (if any):**
Traceback (most recent call last):
  File "<pyshell#1>", line 1, in <module>
    c = Color(255)
TypeError: __init__() missing 2 required positional arguments: 'g' and 'b'

**Comment by abhikpal** [comment]
Hey,

> For now here is the bug I encounter

The code on the main branch (and PyPI) is a bit outdated. Since the
color parser was added *after* we did the last developmental release,
`Color(255)` won't work (yet).

There are two things you can do right now:

- Get the latest code from the develop branch. That way you also get
  access to a whole lot of new features (we also have documentation
  here: [p5.rtfd.io/en/develop](https://p5.readthedocs.io/en/develop), and examples here:
  [github.com/p5py/p5-examples](https://github.com/p5py/p5-examples))

- If you want to continue using the older version, you need to
  explicitly provide the red, green, and blue values when you use
  `Color()`. Additionally these values should be in the 0 to 1 range.
  So white would be `Color(1, 1, 1)`, black would be `Color(0, 0, 0)`,
  etc.

>  One of the feature I am waiting the most is the export to PDF

We are prioritizing porting the core Processing API first before
adding PDF support, etc. But hopefully we'll get there soon 😃

Thanks for bringing this up, though! Please let us know if something else
breaks/doesn't work as expected.


—
Abhik

**Comment by artyprog** [comment]
Thank you.
Betwise here are some work I ve done on the same subject:

[http://salvatore.pythonanywhere.com/RapydBox/default/editor](http://salvatore.pythonanywhere.com/RapydBox/default/editor)
[http://salvatore.pythonanywhere.com/RapydRay](http://salvatore.pythonanywhere.com/RapydRay)
[http://salvatore.pythonanywhere.com/RapydGlow/default/editor](http://salvatore.pythonanywhere.com/RapydGlow/default/editor)
[http://salvatore.pythonanywhere.com/RapydRay](http://salvatore.pythonanywhere.com/RapydRay)

**Comment by abhikpal** [comment]
Interesting! I shall take a look. I'm assuming I can find the source code on your Github?

**Comment by artyprog** [comment]
Thanks :-)

Here is the link for RapydBox, others are only adpatation.
As suggested  the desktop version is  better, it runs with node-webkit (nwjs).
Run the samples from the sketches folder, there are some pretty ones.

It's a little old now more than 4 years...

[https://github.com/artyprog/RapydBox](https://github.com/artyprog/RapydBox)

RapydBox mainly use two lib 
   - [RapydScript](https://github.com/atsepkov/RapydScript)
   - [http://www.clips.ua.ac.be/pages/pattern-canvas](http://www.clips.ua.ac.be/pages/pattern-canvas)

**Comment by abhikpal** [comment]
Ahhh.. I see. I don't think I'll be able to pull in code (at least not
directly) from RapydBox. We want p5 to be a standard Python library so
that it can be used with other packages in the Python ecosystem.

But thanks for the links, I shall take a look at them in general.

**Comment by abhikpal** [comment]
The new version fixes this :)
