### ISSUE TITLE
glfw doesn't find but installed

### ISSUE THREAD

**Issue by gerardPaulLive** [p5py/p5#76]
Hello,

When i try the p5py, from p5 import *, doesn't work. 
The answer is "RuntimeError: Could not import backend "Glfw":
GLFW library not found"

But all packages are installed glfw, numpy, vispy and p5.
i work on windows os.

Thanks.

**Comment by abhikpal** [comment]
what operating system are you on? You might have to install GLFW for your system separately.

**Comment by dbhavsar76** [comment]
For windows, download pre-compiled binaries corresponding to your architecture that is 32 bit or 64 bit, from glfw.org .
extract the folder anywhere you like, i would prefer C drive.
In that folder there is a folder called lib-mingw-w64/w32,
add that to the PATH variable. That should solve the problem.

**Comment by gerardPaulLive** [comment]
Hello,

Thanks for your answer.

**Comment by abhikpal** [comment]
@gerardPaulLive, is your issue solved, then?

**Comment by abhikpal** [comment]
@gerardPaulLive, is your issue solved, then?

**Comment by kltzdsgiorgos** [comment]
I have the same problem as gerardPaulLive but the issue is not solved with the above recommendation.
I tried both the 64 and 32 bit versions from glfw.org.
I am on Windows 10 64 bit.
I tried the user PATH variable
and the system Path variable
Still get the same error
Every dependency is installed

**Comment by dbhavsar76** [comment]
Hello,
First of all, I am very sorry for not so detailed answer, i am new in this.
Now the solution,
I deleted everything related to python and p5 and started from zero to understand this.
I installed **python-3.7.1-amd64.exe**, version doesn't matter, note that its **64 bit**.
Then i did
> pip install p5

it installed p5 and its dependencies : p5, vispy, pillow, numpy, glfw

Now, If we run `from p5 import *` it gives the error

> RuntimeError: Could not import backend "Glfw":
GLFW library not found

For this, I downloaded the **64-bit windows binaries** from https://www.glfw.org/download
and extracted the zip in **C:\\** 
Then added the path(which contains the **glfw3.dll** file)

> C:\\glfw-3.2.1.bin.WIN64\\lib-mingw-w64

to user path environment variable.
Now running the import works fine.

But if we install **32-bit version** of python 
we need to download **32-bit windows binaries** of glfw and add the path with the dll file, which will be

> C:\\glfw-3.2.1.bin.WIN32\\lib-mingw

If we use 32-bit binaries with 64-bit python or otherwise, we get following error

> RuntimeError: Could not import backend "Glfw":
[WinError 193] %1 is not a valid Win32 application

The keypoint is your python and glfw binaries must be same 64-bit (or 32-bit).
If you are not sure which architecture your python has, type `python` in command promt and you will get python shell like this and it is written in there
For 32-bit python,
> Python 3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:05:16) [MSC v.1915 **32 bit (Intel)**] on win32
Type "help", "copyright", "credits" or "license" for more information.
\>\>\>

For 64-bit python,

> Python 3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:57:15) [MSC v.1915 **64 bit (AMD64)**] on win32
Type "help", "copyright", "credits" or "license" for more information.
\>\>\>

Hope that solves the issue.

**Comment by kltzdsgiorgos** [comment]
Followed every step and now i can import without problems,
Thanks a lot

**Comment by XinYaanZyoy** [comment]
i had same issue and it has been solved by following the instructions of @dbhavsar76 ; this issue need to be closed!!

**Comment by Icebear1998** [comment]
> Hello,
> First of all, I am very sorry for not so detailed answer, i am new in this.
> Now the solution,
> I deleted everything related to python and p5 and started from zero to understand this.
> I installed **python-3.7.1-amd64.exe**, version doesn't matter, note that its **64 bit**.
> Then i did
> 
> > pip install p5
> 
> it installed p5 and its dependencies : p5, vispy, pillow, numpy, glfw
> 
> Now, If we run `from p5 import *` it gives the error
> 
> > RuntimeError: Could not import backend "Glfw":
> > GLFW library not found
> 
> For this, I downloaded the **64-bit windows binaries** from https://www.glfw.org/download
> and extracted the zip in **C:\**
> Then added the path(which contains the **glfw3.dll** file)
> 
> > C:\glfw-3.2.1.bin.WIN64\lib-mingw-w64
> 
> to user path environment variable.
> Now running the import works fine.
> 
> But if we install **32-bit version** of python
> we need to download **32-bit windows binaries** of glfw and add the path with the dll file, which will be
> 
> > C:\glfw-3.2.1.bin.WIN32\lib-mingw
> 
> If we use 32-bit binaries with 64-bit python or otherwise, we get following error
> 
> > RuntimeError: Could not import backend "Glfw":
> > [WinError 193] %1 is not a valid Win32 application
> 
> The keypoint is your python and glfw binaries must be same 64-bit (or 32-bit).
> If you are not sure which architecture your python has, type `python` in command promt and you will get python shell like this and it is written in there
> For 32-bit python,
> 
> > Python 3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:05:16) [MSC v.1915 **32 bit (Intel)**] on win32
> > Type "help", "copyright", "credits" or "license" for more information.
> > >>>
> 
> For 64-bit python,
> 
> > Python 3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:57:15) [MSC v.1915 **64 bit (AMD64)**] on win32
> > Type "help", "copyright", "credits" or "license" for more information.
> > >>>
> 
> Hope that solves the issue.

thanks a lot <3

**Comment by pramitd** [comment]
Just for the getting it out there:
I face the same issue on a conda virtual env that I was using with both jupyter and spyder. 
Downloading the extracting the Glfw binaries didn't work. 
The solution was as bellow:

Activate the conda virtual enviroment (venv)
`conda activate tensorflow`

Here tensorflow is my venv

Uninstall previous p5 installation
`pip uninstall p5`

install glfw from conda-forge within the venv
`conda install -c conda-forge glfw`

Reinstall p5
`pip install p5`

Finally restart the spyder/jupyter kernel

**Comment by ivankeller** [comment]
> Just for getting it out there:
> 
> I faced the same issue on a conda virtual env that I was using with both jupyter and spyder.
> Downloading the extracting the Glfw binaries didn't work.
> The solution was as bellow:
> 
> Activate the conda virtual enviroment (venv)
> `conda activate tensorflow`
> 
> Here tensorflow is my venv
> 
> Uninstall previous p5 installation
> `pip uninstall p5`
> 
> install glfw from conda-forge within the venv
> `conda install -c conda-forge glfw`
> 
> Reinstall p5
> `pip install p5`
> 
> Finally restart the spyder/jupyter kernel

this answer also solves the problem on MacOS. Thanks @pramitd !

**Comment by cb-mukundhan** [comment]
for mac install using brew

```
brew install glfw3
```

**Comment by PeterAvgerinos** [comment]
I have the same issue after brew install glfw3, on Mac M1.
