### ISSUE TITLE
Vector's magnitude decreases when the vector is rotated.

### ISSUE THREAD

**Issue by artyprog** [p5py/p5#8]
Hy,

When you animate a vector v with
 v.rotate
The magnitude decrease, in fact  his is  expected.
How would you deal with it ?

Regards

```python
v = Vector(0, 100)
def draw():
    global dt
    dt += 0.1
    v.rotate(dt)
    print(v.magnitude)
```

**Expected behavior:**
10000
**Actual behavior**
9999.999800000001
9999.999000000096
9999.997200000898
9999.994000004783
9999.989000018197
9999.981800055495
9999.97200014456
9999.959200334686
9999.94300070696
9999.923001387619
9999.898802564643

**Errors produced (if any):**

**p5 version:**

**Python version:**
**Operating System:**

**Comment by abhikpal** [comment]
In fact, it goes all the way down to zero when you rotate it enough times!

``` python
>>> import p5
>>> v = p5.Vector(0, 100)
>>> dt = 0.1
>>> for _ in range(10000):
...     v.rotate(dt)
...     dt += 0.1
... 
>>> v.magnitude
0.0
```

Thanks for pointing this out! I'll see what's going on.

**Comment by abhikpal** [comment]
I've pushed a fix on the develop branch.

Turns out when we used

``` python
>>> v = Vector(0, 100)
```

to initialize our vector the internal array saved this information as integers. This meant that we lost some precision whenever the vector was rotated. Explicitly converting the components to floats when the vector is created solved the issue.

I've pushed a fix on the develop branch. We'll merge this into master when we do the next release.
